# Generated by Django 5.0.9 on 2025-12-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('bank', models.CharField(choices=[('SBI Card', 'SBI Card'), ('ICICI Bank', 'ICICI Bank'), ('HDFC Bank', 'HDFC Bank'), ('Axis Bank', 'Axis Bank'), ('HSBC', 'HSBC'), ('American Express', 'American Express'), ('AU Small Finance Bank', 'AU Small Finance Bank'), ('IDFC First Bank', 'IDFC First Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('RBL Bank', 'RBL Bank'), ('Federal Bank', 'Federal Bank'), ('Yes Bank', 'Yes Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Standard Chartered', 'Standard Chartered')], max_length=255, verbose_name='Bank')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Category')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
                ('annual_fee', models.CharField(blank=True, max_length=255, verbose_name='Annual Fee')),
                ('reward_rate', models.CharField(blank=True, max_length=255, verbose_name='Reward Rate')),
                ('fx_markup', models.CharField(blank=True, max_length=255, verbose_name='Forex Markup')),
                ('best_for', models.CharField(blank=True, max_length=255, verbose_name='Best For')),
                ('verdict', models.TextField(blank=True, verbose_name='Verdict')),
                ('detailed_guide', models.TextField(blank=True, verbose_name='Detailed Guide')),
                ('apply_link', models.URLField(blank=True, verbose_name='Apply Link')),
                ('features', models.JSONField(default=list, verbose_name='Features')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
