# Generated by Django 6.0 on 2025-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='bank',
            field=models.CharField(choices=[('SBI Card', 'SBI Card'), ('ICICI Bank', 'ICICI Bank'), ('HDFC Bank', 'HDFC Bank'), ('Axis Bank', 'Axis Bank'), ('HSBC', 'HSBC'), ('American Express', 'American Express'), ('AU Small Finance Bank', 'AU Small Finance Bank'), ('IDFC First Bank', 'IDFC First Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('RBL Bank', 'RBL Bank'), ('Federal Bank', 'Federal Bank'), ('Yes Bank', 'Yes Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Standard Chartered', 'Standard Chartered')], db_index=True, max_length=255, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Category'),
        ),
    ]
