# Generated by Django 5.0.9 on 2025-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_alter_creditcard_bank_alter_creditcard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='reward_caps',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reward Caps'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='reward_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Reward Type'),
        ),
    ]
