# Generated by Django
import json
import os
from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0003_creditcard_reward_caps_creditcard_reward_type'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
