# Generated by Django 5.0.9 on 2026-01-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0004_auto_20251231_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='annual_fee',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='best_for',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='fx_markup',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='reward_caps',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='reward_rate',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='reward_type',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='eligibility',
            field=models.JSONField(blank=True, default=dict, verbose_name='Eligibility'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='fees',
            field=models.JSONField(blank=True, default=dict, verbose_name='Fees'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='rewards',
            field=models.JSONField(blank=True, default=dict, verbose_name='Rewards'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Features'),
        ),
    ]
