# Generated by Django data migration

from django.db import migrations
import json
import os
from django.conf import settings

def update_links(apps, schema_editor):
    CreditCard = apps.get_model('credit_cards', 'CreditCard')
    
    # Path inside the container where we copied the file
    json_path = '/app/creditCards.json'
    
    if not os.path.exists(json_path):
        # Fallback to try relative path if run locally or different mount
        base_dir = settings.BASE_DIR
        json_path = os.path.join(os.path.dirname(base_dir), 'src', 'data', 'creditCards.json')

    if not os.path.exists(json_path):
        print(f"File not found: {json_path}")
        return

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON: {e}")
        return

    updated_count = 0
    
    for item in data:
        card_name = item.get('name')
        link = item.get('link')
        
        if card_name and link:
            # Match directly by name
            cards = CreditCard.objects.filter(name=card_name)
            for cc in cards:
                if cc.apply_link != link:
                    print(f"Updating '{card_name}' -> {link}")
                    cc.apply_link = link
                    cc.save()
                    updated_count += 1
    
    print(f"Updated {updated_count} cards from JSON source.")

class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0005_remove_creditcard_annual_fee_and_more'),
    ]

    operations = [
        migrations.RunPython(update_links, reverse_code=migrations.RunPython.noop),
    ]
