# Generated by Django 5.0.9 on 2025-12-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Platform Name')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('logo', models.URLField(blank=True, verbose_name='Logo URL')),
                ('category', models.CharField(choices=[('Shopping', 'Shopping'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Grocery', 'Grocery'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Health', 'Health'), ('Other', 'Other')], max_length=50, verbose_name='Category')),
                ('site_link', models.URLField(blank=True, verbose_name='Site Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Alias Name')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(blank=True, max_length=255, verbose_name='Cap')),
                ('fee', models.CharField(blank=True, max_length=255, verbose_name='Fee')),
                ('denominations', models.JSONField(default=list, verbose_name='Denominations')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.platform')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='vouchers.voucher')),
            ],
        ),
    ]
