# Generated by Django 5.0.9 on 2025-12-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherplatform',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='platform',
            name='icon_url',
            field=models.URLField(blank=True, verbose_name='Icon URL'),
        ),
        migrations.AddField(
            model_name='voucherplatform',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
