# Generated by Django 6.0 on 2025-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_voucherplatform_options_platform_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Grocery', 'Grocery'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Health', 'Health'), ('Other', 'Other')], db_index=True, max_length=50, verbose_name='Category'),
        ),
    ]
