# Generated by Django 5.0.9 on 2025-12-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_voucher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherplatform',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='External ID'),
        ),
    ]
