# Generated by Django 5.0.9 on 2025-12-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_voucherplatform_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='External ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('gift_card_name', models.CharField(max_length=255, verbose_name='Gift Card Name')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Raw Data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='vouchers.platform')),
            ],
            options={
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
