# Generated by Django 5.0.9 on 2025-12-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_vouchermismatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermismatch',
            name='match_with_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mismatches', to='vouchers.voucher', verbose_name='Map to Voucher'),
        ),
    ]
