# Generated by Django
import json
import os
from django.conf import settings
from django.db import migrations

# Platform logos hardcoded from src/utils/platformLogos.js
PLATFORM_STYLES = {
    "iShop": {
        "logo": "https://d35fe9hjas7aql.cloudfront.net/ishop1.0/prod/shared-ui/v1/assets/images/icons/logo.svg",
    },
    "Gyftr": {
        "logo": "https://www.gyftr.com/instantvouchers/static/images/logo_gv.svg",
    },
    "MagicPin": {
        "logo": "https://cdn.brandfetch.io/idYiJB0V8Y/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1667563687342",
    },
    "Maximize": {
        "logo": "https://www.google.com/s2/favicons?domain=www.maximize.money&sz=128",
    },
    "Amazon": {
        "logo": "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/amazon-white-icon.svg",
    },
    "SaveSage": {
        "logo": "https://savesage.club/SaveSage-Symbol-on-Light-Background.png",
    }
}

def load_vouchers(apps, schema_editor):
    Voucher = apps.get_model('vouchers', 'Voucher')
    Platform = apps.get_model('vouchers', 'Platform')
    VoucherPlatform = apps.get_model('vouchers', 'VoucherPlatform')
    VoucherAlias = apps.get_model('vouchers', 'VoucherAlias')

    # 1. Populate Platforms
    for p_name, p_data in PLATFORM_STYLES.items():
        Platform.objects.update_or_create(
            name=p_name,
            defaults={'icon_url': p_data.get('logo', '')}
        )

    # 2. Populate Vouchers
    # Try different paths for vouchers.json
    paths_to_try = [
        os.path.join(settings.BASE_DIR, 'vouchers.json'),
        '/app/vouchers.json',
        'vouchers.json',
    ]
    file_path = None
    for p in paths_to_try:
        if os.path.exists(p):
            file_path = p
            break
            
    if not file_path:
        print("Warning: vouchers.json not found, skipping voucher population.")
        return

    with open(file_path, 'r') as f:
        data = json.load(f)

    for item in data:
        name = item.get('brand')
        logo = item.get('logo', '')
        category = item.get('category', 'Other')
        site_link = item.get('site', '')

        # Using get_or_create then save to handle updates if needed, 
        # or update_or_create if we want to enforce file data.
        # Logic from populate_vouchers.py was: get_or_create, then update fields if exists.
        
        voucher, created = Voucher.objects.get_or_create(
            name=name,
            defaults={
                'logo': logo,
                'category': category,
                'site_link': site_link
            }
        )
        
        # Update always to match file
        if not created:
            voucher.logo = logo
            voucher.category = category
            voucher.site_link = site_link
            voucher.save()

        platforms_data = item.get('platforms', [])
        
        for i, p_data in enumerate(platforms_data):
            p_name = p_data.get('name')
            if not p_name:
                continue

            platform, _ = Platform.objects.get_or_create(name=p_name)

            VoucherPlatform.objects.update_or_create(
                voucher=voucher,
                platform=platform,
                defaults={
                    'cap': p_data.get('cap', ''),
                    'fee': p_data.get('fee', ''),
                    'denominations': p_data.get('denominations', []),
                    'link': p_data.get('link', ''),
                    'color': p_data.get('color', ''),
                    'priority': i
                }
            )

    # 3. Populate Aliases
    alias_paths_to_try = [
        os.path.join(settings.BASE_DIR, 'brand_aliases.json'),
        '/app/brand_aliases.json',
        'brand_aliases.json',
    ]
    alias_file_path = None
    for p in alias_paths_to_try:
        if os.path.exists(p):
            alias_file_path = p
            break

    if not alias_file_path:
        print("Warning: brand_aliases.json not found, skipping alias population.")
        return

    with open(alias_file_path, 'r') as f:
        alias_data = json.load(f)
    
    for alias_name, voucher_name in alias_data.items():
        # Find the target voucher.
        voucher = Voucher.objects.filter(name__iexact=voucher_name).first()
        if not voucher:
             continue
        
        VoucherAlias.objects.get_or_create(
            name=alias_name,
            voucher=voucher
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_vouchermismatch_match_with_voucher'),
    ]

    operations = [
        migrations.RunPython(load_vouchers, migrations.RunPython.noop),
    ]
