# Generated by Django 4.2.27 on 2026-01-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0007_auto_20251231_1103"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voucherplatform",
            unique_together={("voucher", "platform")},
        ),
    ]
