# Generated by Django 5.0.9 on 2026-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_add_unique_voucher_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='site_link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Site Link'),
        ),
    ]
