# Generated by Django 5.0.9 on 2026-01-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_add_unique_voucher_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('link_token', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Link Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('subscribe_all', models.BooleanField(default=True, verbose_name='Subscribe to All')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Subscription',
                'verbose_name_plural': 'Telegram Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='voucherplatform',
            name='last_stock_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Stock Check'),
        ),
        migrations.AddField(
            model_name='voucherplatform',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock Count'),
        ),
        migrations.AddField(
            model_name='voucherplatform',
            name='was_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Was Out of Stock'),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.IntegerField(default=0, verbose_name='Previous Stock')),
                ('new_stock', models.IntegerField(default=0, verbose_name='New Stock')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('voucher_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='vouchers.voucherplatform')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_subscriptions', to='vouchers.telegramsubscription')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscriptions', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Subscription',
                'verbose_name_plural': 'Voucher Subscriptions',
                'unique_together': {('subscription', 'voucher')},
            },
        ),
    ]
