# Generated by Django 4.2.27 on 2026-02-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0009_alter_voucher_logo_alter_voucher_site_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherplatform",
            name="out_of_stock_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Out of Stock At"
            ),
        ),
    ]
