# Generated by Django 5.0.9 on 2025-12-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('embed_html', models.TextField(blank=True, verbose_name='Embed HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
