# Generated by Django
import json
import os
from django.conf import settings
from django.db import migrations

def load_guides(apps, schema_editor):
    Guide = apps.get_model('guides', 'Guide')
    
    paths_to_try = [
        os.path.join(settings.BASE_DIR, 'guides.json'),
        '/app/guides.json',
        'guides.json',
    ]
    json_file_path = None
    for p in paths_to_try:
        if os.path.exists(p):
            json_file_path = p
            break
            
    if not json_file_path:
        print("Warning: guides.json not found, skipping guides population.")
        return

    with open(json_file_path, "r") as f:
        guides_data = json.load(f)

    for item in guides_data:
        try:
            Guide.objects.update_or_create(
                id=item.get("id"),
                defaults={
                    "title": item.get("title"),
                    "description": item.get("description"),
                    "link": item.get("link"),
                    "tags": item.get("tags", []),
                    "author": item.get("author"),
                    "embed_html": item.get("embedHtml", ""),
                }
            )
        except Exception as e:
            print(f"Error importing guide {item.get('title')}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_guides, migrations.RunPython.noop),
    ]
