# Generated by Django 5.0.9 on 2026-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guidepage_guidepagetag_delete_guide_guidepage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepage',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guidepage',
            name='external_link',
            field=models.URLField(blank=True),
        ),
    ]
